name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out
        uses: actions/checkout@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and Push Jenkins Base
        uses: docker/build-push-action@v2
        with:
          context: ./jenkins-base/
          file: jenkins-base/Dockerfile
          push: true
          tags: ghcr.io/ragin-lundf/k8s-jenkins-docker/k8s-jcasc-jenkins-base:latest
      -
        name: Build and Push Jenkins Java Base
        uses: docker/build-push-action@v2
        with:
          context: ./jenkins-java/
          file: jenkins-java/Dockerfile
          push: true
          tags: ghcr.io/ragin-lundf/k8s-jenkins-docker/k8s-jcasc-jenkins-base-java:latest
